/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuthBranchUsers {
  assigned_at: Generated<Timestamp>;
  branch_id: string;
  id: Generated<string>;
  user_id: string;
}

export interface AuthPermissions {
  action_key: string;
  description: string;
  id: Generated<Int8>;
  module_key: string;
}

export interface AuthRateLimitBuckets {
  count: number;
  key_hash: string;
  reset_at: Timestamp;
  scope: string;
}

export interface AuthRefreshTokens {
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  family_id: string;
  id: Generated<string>;
  replaced_by_id: string | null;
  revoked_at: Timestamp | null;
  token_hash: string;
}

export interface AuthRolePermissions {
  created_at: Generated<Timestamp>;
  permission_id: Int8;
  role_id: Int8;
}

export interface AuthRoles {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  is_active: Generated<boolean>;
  is_system: Generated<boolean>;
  role_name: string;
  updated_at: Generated<Timestamp>;
}

export interface AuthSessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  revoked_at: Timestamp | null;
  token_hash: string;
  user_id: string;
}

export interface AuthTokenFamilies {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  revoked_at: Timestamp | null;
  user_id: string;
}

export interface AuthUsers {
  contact_number: string;
  created_at: Generated<Timestamp>;
  email: string;
  full_name: string;
  hashed_password: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  role_id: Int8;
  updated_at: Generated<Timestamp>;
}

export interface Branches {
  address: string | null;
  branch_name: string;
  code: string;
  created_at: Generated<Timestamp>;
  date_opened: Timestamp | null;
  has_dine_in: Generated<boolean>;
  id: Generated<string>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface BranchInventory {
  branch_id: string;
  quantity_on_hand: Generated<Numeric>;
  stock_item_id: string;
  updated_at: Generated<Timestamp>;
}

export interface CommissaryInventory {
  quantity_on_hand: Generated<Numeric>;
  stock_item_id: string;
  updated_at: Generated<Timestamp>;
}

export interface InventoryMovements {
  actor_user_id: string;
  branch_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  idempotency_key: string | null;
  inventory_scope: string;
  movement_type: string;
  quantity_delta: Numeric;
  reason: string | null;
  stock_item_id: string;
  supplier_receipt_item_id: string | null;
}

export interface Products {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  product_name: string;
  updated_at: Generated<Timestamp>;
}

export interface StockItems {
  category: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  stock_item_name: string;
  unit: string;
  updated_at: Generated<Timestamp>;
}

export interface SupplierReceiptItems {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  quantity_received: Numeric;
  stock_item_id: string;
  supplier_receipt_id: string;
  unit_cost: Numeric;
}

export interface SupplierReceipts {
  created_at: Generated<Timestamp>;
  created_by_user_id: string;
  id: Generated<string>;
  idempotency_key: string;
  posted_at: Timestamp | null;
  posted_by_user_id: string | null;
  received_at: Timestamp;
  status: Generated<string>;
  supplier_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Suppliers {
  address: string | null;
  contact_number: string | null;
  contact_person: string | null;
  created_at: Generated<Timestamp>;
  email: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  supplier_name: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  "auth.branch_users": AuthBranchUsers;
  "auth.permissions": AuthPermissions;
  "auth.rate_limit_buckets": AuthRateLimitBuckets;
  "auth.refresh_tokens": AuthRefreshTokens;
  "auth.role_permissions": AuthRolePermissions;
  "auth.roles": AuthRoles;
  "auth.sessions": AuthSessions;
  "auth.token_families": AuthTokenFamilies;
  "auth.users": AuthUsers;
  branch_inventory: BranchInventory;
  branches: Branches;
  commissary_inventory: CommissaryInventory;
  inventory_movements: InventoryMovements;
  products: Products;
  stock_items: StockItems;
  supplier_receipt_items: SupplierReceiptItems;
  supplier_receipts: SupplierReceipts;
  suppliers: Suppliers;
}
